services:
  - type: web
    name: mywebsite
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      gunicorn mywebsite.wsgi